apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJWR2hsYjI1c2VVbzZaMmh3WDBod2MzcHlUVFJuU0cxS1NsUlRXVU00VmxNMU1VaEdNazlEU2psMlNURkdUMDlXV0E9PSIKCQl9Cgl9LAoJImNyZWRzU3RvcmUiOiAiZGVza3RvcCIsCgkiY3VycmVudENvbnRleHQiOiAiZGVza3RvcC1saW51eCIKfQ==
type: kubernetes.io/dockerconfigjson
